/**
 * API Worker Skill - v0.2.0
 *
 * API design and implementation specialist.
 */

import type { SkillHandler } from "../framework.js";

export const apiWorkerSkill: SkillHandler = async (args, context) => {
  const task = args.task as string;
  const style = args.style as string | undefined;

  // silent

  const mockOutput = `## API Design

### Task
${task}

### Design Decisions
- **Style:** ${style || "RESTful"}
- **Authentication:** JWT Bearer
- **Rate Limiting:** 100 req/min
- **Versioning:** URL path (/v1/)

### Endpoints

#### GET /api/resource
\`\`\`typescript
// List resources with pagination
interface ListRequest {
  page?: number;
  limit?: number;
  sort?: string;
}

interface ListResponse {
  data: Resource[];
  meta: PaginationMeta;
}
\`\`\`

#### POST /api/resource
\`\`\`typescript
// Create new resource
interface CreateRequest {
  name: string;
  data: unknown;
}

interface CreateResponse {
  id: string;
  created: boolean;
}
\`\`\`

### Error Handling
\`\`\`typescript
interface ApiError {
  error: {
    code: string;
    message: string;
    details?: Record<string, unknown>;
  };
}
\`\`\`

### Implementation
\`\`\`typescript
// src/app/api/resource/route.ts
import { NextRequest, NextResponse } from 'next/server';

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  // Implementation...
  return NextResponse.json({ data: [] });
}
\`\`\`

---
*Generated by API Worker Skill*
`;

  return {
    success: true,
    output: mockOutput,
    artifacts: [
      "src/app/api/resource/route.ts",
      "src/types/api.ts",
    ],
  };
};

export default apiWorkerSkill;
